stages:
  - build
  - test
  - sonar
  - package
  - deploy

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"
  DOCKER_DRIVER: overlay2

cache:
  paths:
    - .m2/repository

maven-build:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn compile --batch-mode

unit-and-integration-tests:
  stage: test
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn test jacoco:report --batch-mode
  artifacts:
    when: always
    reports:
      junit:
        - "**/target/surefire-reports/TEST-*.xml"
    paths:
      - "**/target/site/jacoco/"

sonarqube-check:
  stage: sonar
  image: maven:3.9.6-eclipse-temurin-17
  dependencies:
    - unit-and-integration-tests
  script:
    - >
      mvn sonar:sonar
      -Dsonar.host.url=$SONAR_HOST_URL
      -Dsonar.login=$SONAR_TOKEN
  only:
    - main
    - develop

docker-build:
  stage: package
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build -f docker/Dockerfile.gateway -t $CI_REGISTRY_IMAGE/api-gateway:$CI_COMMIT_SHORT_SHA .
    - docker build -f docker/Dockerfile.order -t $CI_REGISTRY_IMAGE/order-service:$CI_COMMIT_SHORT_SHA .
    - docker build -f docker/Dockerfile.payment -t $CI_REGISTRY_IMAGE/payment-service:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE/api-gateway:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/order-service:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/payment-service:$CI_COMMIT_SHORT_SHA
  only:
    - main

k8s-deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl apply -f k8s/namespace.yaml
    - kubectl apply -f k8s/config-and-secrets.yaml
    - kubectl apply -f k8s/api-gateway-deployment.yaml
    - kubectl apply -f k8s/order-service-deployment.yaml
    - kubectl apply -f k8s/payment-service-deployment.yaml
    - kubectl apply -f k8s/ingress.yaml
  only:
    - main
  environment:
    name: production
    url: https://api.fintech.enterprise.internal
