# SonarQube Project Configuration
sonar.projectKey=fintech-enterprise-platform
sonar.projectName=Fintech Enterprise Platform
sonar.projectVersion=1.0.0

# Source & Test paths
sonar.sources=common-contracts/src/main/java,api-gateway/src/main/java,order-service/src/main/java,payment-service/src/main/java,legacy-core-accounting/src/main/java
sonar.tests=legacy-core-accounting/src/test/java,order-service/src/test/java,payment-service/src/test/java,api-gateway/src/test/java

# Encoding
sonar.sourceEncoding=UTF-8
sonar.java.source=21

# JaCoCo XML Coverage Report path
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml

# Code Quality Gate Rules & Exclusions
sonar.exclusions=**/generated-sources/**,**/proto/**,**/domain/Q*.java
sonar.coverage.exclusions=**/config/**,**/dto/**,**/domain/**,**/ApiGatewayApplication.java,**/OrderServiceApplication.java,**/PaymentServiceApplication.java

# Quality Gates: Minimum 80% line coverage, 0 Blocker/Critical bugs
sonar.qualitygate.wait=true
