apiVersion: v1
kind: ConfigMap
metadata:
  name: fintech-config
  namespace: fintech-platform
data:
  REDIS_HOST: "fintech-redis"
  REDIS_PORT: "6379"
  ACTIVEMQ_BROKER_URL: "tcp://fintech-activemq:61616"
  MINIO_URL: "http://fintech-minio:9000"
  LOKI_URL: "http://fintech-loki:3100/loki/api/v1/push"
  ZIPKIN_URL: "http://fintech-zipkin:9411/api/v2/spans"
  PAYMENT_GRPC_HOST: "payment-service"
  PAYMENT_GRPC_PORT: "9090"
---
apiVersion: v1
kind: Secret
metadata:
  name: fintech-secrets
  namespace: fintech-platform
type: Opaque
stringData:
  JWT_SECRET: "EnterpriseSuperSecureSecretKeyThatIsAtLeast32BytesLong!"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  ORACLE_USERNAME: "fintech_user"
  ORACLE_PASSWORD: "fintech_pass"
